### ISSUE TITLE
Probleme d'execution sur la route /api/init/data

### ISSUE THREAD

**Issue by HayaAouate** [studoo-app/mock-veliko-api#9]
Voici la log 👍 
`
<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/mock-veliko-api/app/Repository/VeloRepository.php on line <i>36</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0004</td><td bgcolor='#eeeeec' align='right'>437328</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/mock-veliko-api/public/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>521248</td><td bgcolor='#eeeeec'>Studoo\EduFramework\Core\LoadCouchCore->run(  )</td><td title='/var/www/mock-veliko-api/public/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>42</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0766</td><td bgcolor='#eeeeec' align='right'>545088</td><td bgcolor='#eeeeec'>Studoo\EduFramework\Core\Controller\FastRouteCore->getRoute(  )</td><td title='/var/www/mock-veliko-api/vendor/studoo/edu-framework/src/EduFramework/Core/LoadCouchCore.php' bgcolor='#eeeeec'>.../LoadCouchCore.php<b>:</b>49</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0787</td><td bgcolor='#eeeeec' align='right'>547536</td><td bgcolor='#eeeeec'>Controller\api\InitController->execute( <span>$request = </span><span>class Studoo\EduFramework\Core\Controller\Request { private string $httpMethod = &#39;GET&#39;; private string $route = &#39;/api/init/data&#39;; private string $hander = &#39;Controller\\api\\InitController&#39;; private array $vars = [] }</span> )</td><td title='/var/www/mock-veliko-api/vendor/studoo/edu-framework/src/EduFramework/Core/Controller/FastRouteCore.php' bgcolor='#eeeeec'>.../FastRouteCore.php<b>:</b>156</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>67.6447</td><td bgcolor='#eeeeec' align='right'>5927416</td><td bgcolor='#eeeeec'>Repository\VeloRepository->insert( <span>$item = </span><span>[&#39;type&#39; =&gt; &#39;mechanical&#39;, &#39;status&#39; =&gt; &#39;available&#39;, &#39;num_km_total&#39; =&gt; 252, &#39;station_id_available&#39; =&gt; 13912564]</span> )</td><td title='/var/www/mock-veliko-api/app/Controller/api/InitController.php' bgcolor='#eeeeec'>.../InitController.php<b>:</b>89</td></tr>
</table></font>
`

**Comment by bfoujols** [comment]
@HayaAouate  Merci pour ton message, la correction est en cours !

**Comment by bfoujols** [comment]
Fix deploy ;)
